abbr dc "docker-compose"
abbr dcb "docker-compose build"
abbr dcu "docker-compose up -d"
abbr dcd "docker-compose down"
abbr dcpf "docker-compose --profile full"
abbr dcpfb "docker-compose --profile full build"
abbr dcpfu "docker-compose --profile full up -d --build"
abbr dcpfd "docker-compose --profile full down"
abbr dcs "docker-compose stop"
abbr dcst "docker-compose start"
abbr dstop "docker stop (docker ps -a -q) && docker rm (docker ps -a -q)"
